development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: booker
  password: boooks
  timeout: 5000
  database: books_dev

test:
  <<: *default
  database: books_tests

production:
  <<: *default
  database: books_prod
